name: CI Pipeline

on: 
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # match engines in package.json
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint ESLint
        run: npm run lint

      - name: Run Prettier (write mode)
        run: npm run prettier

      - name: Run Jest tests
        env: 
          CI: true
        run: npm run test

      - name: Build react app
        run: npm run build